title: Dcycle Blog
description: Drupal automated tests, continuous integration

url: http://blog.dcycle.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-redirect-from]
paginate: 50

navigation:
 - title: Blog
   url: /
 - title: Manifesto
   url: /manifesto
 - title: Code snippets
   url: /snippets
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: dcycle
   twitter: dcycleproject
   email: albert@dcycle.com

google_analytics: "UA-25649530-1"
